---
title: "project5"
output: html_document
---
```{r}
library(ggplot2)
library(MASS)
library(tidyr)
library(dplyr)
bank=data.table::fread("D:/USER/Desktop/(r)statistics/BankChurners_new.csv",encoding="UTF-8")
```
#客戶流失vs...
#總交易金額
```{r}
b1=bank %>% dplyr::select(Attrition_Flag,Total_Trans_Amt)
ggplot(b1, aes(x = Attrition_Flag)) + geom_bar(position = "dodge")
b1 %>% group_by(Attrition_Flag) %>% summarise(總交易金額=sum(Total_Trans_Amt))
#獨立#比例
#table(b1)
#chisq.test(table(b1), simulate.p.value = TRUE)
#p=0.0004998拒絕H0，流失與非流失客戶的被聯繫次數比例不一致

471247/(471247+3939207)
779.83*12
b=bank %>% filter(Total_Trans_Amt>(779.83*12)) %>% dplyr::select(Attrition_Flag, Total_Trans_Amt)
ggplot(b, aes(x = Attrition_Flag, fill=Attrition_Flag)) + geom_bar(position = "dodge")
count(b)
77/1019
```
#客戶流失外部資料
流失率0.15
流失0.15/存在0.85
```{r}
attrited=bank %>% filter(Attrition_Flag=="Attrited Customer")
existing=bank %>% filter(Attrition_Flag=="Existing Customer")
count(existing)
b2=bank %>% dplyr::select(Attrition_Flag)
ggplot(b2, aes(x = "", fill = Attrition_Flag)) + geom_bar()+coord_polar(theta="y")
#H0 : 資料分配符合期望值
#H1 : 資料分配不符合期望值
table(b2)
chisq.test(table(b2), p=c(0.15, 0.85))
77/855
#p=0.328不拒絕H0，資料分配符合期望值
```
#收入
```{r}
b3=bank %>% filter(Income_Category!="Unknown") %>% dplyr::select(Attrition_Flag, Income_Category)
b3_new=factor(b3, levels=c("Less than $40K", "$40K - $60K", "$60K - $80K", "$80K - $120K", "$120K +"))
ggplot(b3, aes(x = Income_Category, fill = Attrition_Flag)) + geom_bar(position = "dodge")
#獨立
table(b3)
chisq.test(table(b3))
#同質

```
#性別
```{r}
b4=bank %>% dplyr::select(Attrition_Flag, Gender)
ggplot(b4, aes(x = Gender, fill = Attrition_Flag)) + geom_bar(position = "dodge")
#獨立
table(b4)
chisq.test(table(b4))
#同質
```
#卡類別
```{r}
b5=bank %>% dplyr::select(Attrition_Flag, Card_Category)
ggplot(b5, aes(x = Card_Category, fill = Attrition_Flag)) + geom_bar(position = "dodge")
#獨立
table(b5)
chisq.test(table(b5), simulate.p.value = TRUE)
#同質

```
#教育
```{r}
b6=bank %>% filter(Education_Level!="Unknown") %>% dplyr::select(Attrition_Flag, Education_Level)
ggplot(b6, aes(x = Education_Level, fill = Attrition_Flag)) + geom_bar(position = "dodge")
#獨立#同質
##卡方同質性檢定
#H0 : 流失與非流失客戶的教育程度比例一致
#H1 : 流失與非流失客戶的教育程度比例不一致
table(b6)
chisq.test(table(b6))
#p=0.1895不拒絕H0，流失與非流失客戶的教育程度比例一致
```
#聯繫客戶次數
```{r}
b7=bank %>% dplyr::select(Attrition_Flag, Contacts_Count_12_mon)
ggplot(b7, aes(x = Contacts_Count_12_mon, fill = Attrition_Flag)) + geom_bar(position = "dodge")
#獨立#同質
##卡方同質性檢定
#H0 : 流失與非流失客戶的被聯繫次數比例一致
#H1 : 流失與非流失客戶的被聯繫次數比例不一致
table(b7)
chisq.test(table(b7), simulate.p.value=TRUE)
fisher.test(table(b7), simulate.p.value=TRUE)
#p=0.0004998拒絕H0，流失與非流失客戶的被聯繫次數比例不一致
```